#@ load("@ytt:data", "data")

#@ def labels():
simple-app: ""
#@ end

---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: simple-app
  app.kubernetes.io/name: simple-app
  app.kubernetes.io/instance: simple-app-abcxyz
  app.kubernetes.io/version: #@ data.values.version
  app.kubernetes.io/component: Service
  app.kubernetes.io/part-of: simple-app
  app.kubernetes.io/managed-by: Carvel
spec:
  ports:
  - port: #@ data.values.svc_port
    targetPort: #@ data.values.app_port
  selector: #@ labels()
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: simple-app
  app.kubernetes.io/name: simple-app
  app.kubernetes.io/instance: simple-app-abcxyz
  app.kubernetes.io/version: #@ data.values.version
  app.kubernetes.io/component: Deployment
  app.kubernetes.io/part-of: simple-app
  app.kubernetes.io/managed-by: Carvel
spec:
  selector:
    matchLabels: #@ labels()
  template:
    metadata:
      labels: #@ labels()
    spec:
      containers:
      - name: simple-app
        image:  #@ data.values.image
        env:
        - name: HELLO_MSG
          value: #@ data.values.hello_msg
